version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: pg_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: pg_backend
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      MONGO_URL: "mongodb://mongo:27017"
      DB_NAME: "practice_ground"
      JWT_SECRET: "change-me-to-a-64-char-random-hex-string-in-production-environment"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "admin123"
      FRONTEND_URL: "http://localhost:8080"
    ports:
      - "8001:8001"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: pg_frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  mongo_data:
